version: '3.8'
services:
  database:
    image: postgres:18.1-alpine3.22
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi
    volumes:
      - /home/illia/db_data:/var/lib/postgresql/data
    shm_size: 256mb
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - internalNetwork

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_pr
    env_file:
      - .env
    ports:
      - "7000:7000"
    volumes:
      - ./:/app
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@database:5432/fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 7000 --reload
    networks:
      - internalNetwork

volumes:
  db_data:


networks:
  internalNetwork:
    driver: bridge
